### ISSUE TITLE
[ERROR] attempt to index a nil value (local 'win')

### ISSUE THREAD

**Issue by mapperr** [milhnl/vis-format#1]
Hi!

I've just installed vis-format with [vis-plug](https://github.com/erf/vis-plug),
and mapped to a key like this:

```lua
local plug=require('vis-plug')

local plugins = {
    { 'milhnl/vis-format', alias = 'format' },
}

plug.init(plugins, true)

vis.events.subscribe(vis.events.INIT, function()
    vis:map(vis.modes.NORMAL, " o", plug.plugins.format.apply)
end)
```

but when I try to use it I get this error:

`/home/arch/.cache/vis-plug/plugins/vis-format/init.lua:103: attempt to index a nil value (local 'win')`

that come from this function:

```lua
local apply = function(file, range, pos)
  local win = getwinforfile(file)
  pos = pos or win.selection.pos  -- <-- THIS IS THE LINE 103 PRODUCING THE ERROR
  if range and range.start == 0 and range.finish == win.file.size then
    range = nil
  end
  local formatter = formatters[win.syntax]
  if formatter and formatter.pick then
    formatter = formatter.pick(win)
  end
  if formatter == nil then
    vis:info('No formatter for ' .. win.syntax)
    return pos
  end
  if range ~= nil and not formatter.options.ranged then
    vis:info('Formatter for ' .. win.syntax .. ' does not support ranges')
    return pos
  end
  pos = formatter.apply(win, range) or pos
  vis:insert('') -- redraw and friends don't work
  return pos
end
```

I don't yet have an understanding of vis and the plugin API, I just started reading about it a month ago and using it for a couple of days, so I don't think I can be much of a help, but, well, dunno, maybe I'm missing something in my config?

Thanks a lot for the plugin, anyway : )

**Comment by milhnl** [comment]
Thanks for letting me know!

I think you're the first user other than myself, and there was a bug in there because I wasn't using it as documented. Should be fixed now. I'll be more than happy to help if you run into any other issues.

You'll probably need to run `:plug-update` to update.

Happy hacking!

**Comment by mapperr** [comment]
All good now, thx!
